carts/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.cart,name = "cart"),
    path('add_cart/<int:product_id>/',views.add_cart,name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart,name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item,name="remove_cart_item"),
    path('checkout/',views.checkout,name = "checkout"),
]

ecommerce/urls.py
from django.conf import settings
from ecommerce.settings import MEDIA_ROOT
from django.contrib import admin
from django.urls import path,include
from Eapp.views import home
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('store/',include('store.urls')),
    path('cart/',include('carts.urls')),
    path('accounts/',include('accounts.urls')),
]+static(settings.MEDIA_URL,document_root=MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.store,name = 'store'),
    path('category/<slug:category_slug>/',views.store,name = 'products_by_catrgory'),
    path('category/<slug:category_slug>/<slug:product_slug>/',views.product_details,name = 'product_details'),
    path('search/',views.search,name='search'),
]

Eapp/models.py
from django.db import models
from django.db.models.fields import SlugField
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length = 50,unique=True)
    slug = models.SlugField(max_length=100,unique=True)
    description = models.TextField(max_length=255,blank=True)
    cat_image = models.ImageField(upload_to= "photos/categories",blank = True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('products_by_catrgory',args=[self.slug])

    def __str__(self):
        return self.category_name

carts/models.py
from django.db import models
from accounts.models import Account

from store.models import Product,Variation

# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank = True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id 


class CartItem(models.Model):
    user = models.ForeignKey(Account,on_delete=models.CASCADE,null = True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation,blank = True)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE,null = True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price*self.quantity

    def __unicode__(self):
        return self.product

store/models.py
from django.db.models.deletion import CASCADE
from Eapp.models import Category
from django.db import models
from Eapp.models import Category
from django.urls import reverse
# Create your models here.

class Product(models.Model):
    product_name = models.CharField(max_length=200,unique=True)
    slug = models.SlugField(max_length=200,unique=True)
    description = models.TextField(max_length=500,blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_avaliable = models.BooleanField(default=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    created_date = models.DateField(auto_now_add=True)
    modified_date = models.DateField(auto_now=True)

    def get_url(self):
        return reverse('product_details',args=[self.category.slug,self.slug])

    def __str__(self):
        return self.product_name


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category='color',is_active='True')

    def sizes(self):
        return super(VariationManager,self).filter(variation_category='size',is_active='True')

variation_category_choice = (('color','color'),('size','size'),)

 
class Variation(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100,choices=variation_category_choice)
    variation_value = models.CharField(max_length=100) 
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

Eapp/views.py
from store.models import Product
from django.shortcuts import render
from .models import Category
from store.models import Product

# Create your views here.
def home(request):
    products  = Product.objects.all().filter(is_avaliable=True)
    context = {"products":products,}
    return render(request, "index.html",context)

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

# Create your views here.
from django.http import HttpResponse

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id) #get the product
    product_variation = []
    if request.method == 'POST':
        for item in request.POST:
            key = item
            value = request.POST[key]
            try:
                variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                product_variation.append(variation)
            except:
                pass
    
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
    cart.save()


    is_cart_exists = CartItem.objects.filter(product=product,cart=cart).exists()
    if is_cart_exists:
        cart_item = CartItem.objects.filter(product=product,cart=cart)

        ex_var_list = []
        id = []
        for item in cart_item:
            existing_variation = item.variations.all()
            ex_var_list.append(list(existing_variation))
            id.append(item.id)

        if product_variation in ex_var_list:
            #increase the item quantity
            index = ex_var_list.index(product_variation)
            item_id = id[index]
            item = CartItem.objects.get(product=product,id=item_id)
            item.quantity+=1
            item.save()
        else:
            #create a new cart item
            cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
            if len(product_variation)>0:
                cart_item.variations.clear()
                for item in product_variation:
                    cart_item.variations.add(item)
            cart_item.save()
    else:
        cart_item =  CartItem.objects.create(
            product = product,
            quantity=1,
            cart=cart,
        )
        if len(product_variation)>0:
            cart_item.variations.clear()
            for item in product_variation:
                cart_item.variations.add(item)
        cart_item.save()
    return redirect('cart')


def remove_cart(request, product_id, cart_item_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    try:
        cart_item = CartItem.objects.get(product=product, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass #just ignore

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax'       : tax,
        'grand_total': grand_total,
    }
    return render(request, 'cart.html', context)

@login_required(login_url='login')
def checkout(request,total=0,quantity=0,cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass #just ignore

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax'       : tax,
        'grand_total': grand_total,
    }
    return render(request,"checkout.html",context)

store/views.py
from django.http.response import HttpResponse
from Eapp.models import Category
from django.shortcuts import get_object_or_404, render
from .models import Product
from carts.models import CartItem
from carts.views import _cart_id
from django.db.models import Q

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

# Create your views here.

def store(request,category_slug=None):
    categories = None
    products = None

    if category_slug!=None:
        categories = get_object_or_404(Category,slug=category_slug)
        products = Product.objects.filter(category=categories,is_avaliable=True)
        paginator = Paginator(products,6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_avaliable=True).order_by('id')
        paginator = Paginator(products,6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    context = {"products":paged_products,"product_count":product_count}
    return render(request,'store.html',context)


def product_details(request,category_slug,product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug,slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request),product=single_product).exists()
    except Exception as e:
        raise e

    context = {
        "single_product":single_product,
        "in_cart":in_cart,
    }    

    return render(request,"product-detail.html",context)


def search(request):
    if "keyword" in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
    context = {"products":products,}
    return render(request,'store.html',context)

Eapp/templates/base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
	{%load static%}
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>GreatKart | One of the Biggest Online Shopping Platform</title>

<link href="{%static 'images/favicon.ico'%}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static 'js/jquery-2.0.0.min.js'%}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{%static 'js/bootstrap.bundle.min.js'%}" type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css'%}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/all.min.css'%}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css'%}" rel="stylesheet" type="text/css"/>
<link href="{%static 'css/responsive.css'%}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static 'js/script.js'%}" type="text/javascript"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>

</head>
<body>
{% comment %} navbar {% endcomment %}

{%include 'includes/nav.html'%}

{%block content%}
{%endblock%}

{% comment %} footer {% endcomment %}
<!-- {%include 'includes/footer.html'%} -->

Eapp/templates/cart.html
{%extends 'base.html'%}
{%load static%}
{%block content%}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items%}
	<h2>Your Shoping Cart is Empty</h2>
	<br>
	<div class ="text-center">
		<a href = "{%url 'store'%}" class = "btn btn-primary">Continue Shopping</a>
	</div>
{%else%}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
{%for cart_item in cart_items%}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ cart_item.product.image.url }}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
				<p class="small text-muted">
					{% if cart_item.variations.all %}
						{% for item in cart_item.variations.all %}
							{{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
						{% endfor %}
					{% endif %}
				</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
		<div class="col">
			<div class="input-group input-spinner">
				<div class="input-group-prepend">
				<a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
				</div>
				<input type="text" class="form-control"  value="{{ cart_item.quantity }}">
				<div class="input-group-append">
					<form action="{% url 'add_cart' cart_item.product.id %}" method="POST">
						{% csrf_token %}
						{% for item in cart_item.variations.all %}
							<input type="hidden" name="{{ item.variation_category | lower }}" value="{{ item.variation_value | capfirst }}">
						{% endfor %}
						<button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
					</form>
				</div>
			</div> <!-- input-group.// -->
		</div> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">{{cart_item.sub_total}}</var> 
			<small class="text-muted"> $578.00 each</small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
		<a href="{%url 'remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('Are you sure you want to delete this item')" class="btn btn-danger"> Remove</a>
	</td>
</tr>
{%endfor%}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">${{total}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right">${{tax}} each</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static '/images/misc/payments.png'%}" height="26">
			</p>
			<a href="{% url 'checkout'%}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store'%}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->
	{%endif%}
</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{%endblock%}

Eapp/templates/checkout.html
{%extends 'base.html'%}
{%load static%}
{%block content%}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="row">
	<aside class="col-lg-6">
<div class="card">
    <div class = "card-body">
        <h4 class = "card-title mb-4">Billing Address</h4>
        <form action="" method = "POST">
            {% csrf_token %}
            <div class = "form-row">
                <div class ="col form-group">
                    <label for = "">First Name</label>
                    <input type = "text" name = "first-name" class = "form-control" required>
                </div>
                <div class ="col form-group">
                    <label for = "">Last Name</label>
                    <input type = "text" name = "last-name" class = "form-control" required>
                </div>
            </div>
            <div class = "form-row">
                <div class ="col form-group">
                    <label for = "">Email</label>
                    <input type = "email" name = "email" class = "form-control" required>
                </div>
                <div class ="col form-group">
                    <label for = "">Phone Number</label>
                    <input type = "text" name = "phone" class = "form-control" required>
                </div>
            </div>
            <div class = "form-row">
                <div class ="col form-group">
                    <label for = "">Address Line 1</label>
                    <input type = "text" name = "address_line_1" class = "form-control" required>
                </div>
                <div class ="col form-group">
                    <label for = "">Address Line 2</label>
                    <input type = "text" name = "address_line_2" class = "form-control">
                </div>
            </div>
            <div class = "form-row">
                <div class ="col form-group">
                    <label for = "">City</label>
                    <input type = "text" name = "city" class = "form-control" required>
                </div>
                <div class ="col form-group">
                    <label for = "">State</label>
                    <input type = "text" name = "state" class = "form-control" required>
                </div>
                <div class ="col form-group">
                    <label for = "">Country</label>
                    <input type = "text" name = "country" class = "form-control" required>
                </div>
            </div>
            <div class = "form-row">
                <label for="">Order Note</label>
                <textarea name = "order_note" rows = "2" class = "form-control"></textarea>
            </div>

    </div>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-6">

		<div class="card">
		<div class="card-body">
            <table class="table table-borderless table-shopping-cart">
                <thead class="text-muted">
                <tr class="small text-uppercase">
                  <th scope="col">Product</th>
                  <th scope="col" width="120">Quantity</th>
                  <th scope="col" width="120">Price</th>
                </tr>
                </thead>
                <tbody>
                {%for cart_item in cart_items%}
                <tr>
                    <td>
                        <figure class="itemside align-items-center">
                            <div class="aside"><img src="{{ cart_item.product.image.url }}" class="img-sm"></div>
                            <figcaption class="info">
                                <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                                <p class="small text-muted">
                                    {% if cart_item.variations.all %}
                                        {% for item in cart_item.variations.all %}
                                            {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
                                        {% endfor %}
                                    {% endif %}
                                </p>
                            </figcaption>
                        </figure>
                    </td>
                    <td> 
                        <!-- col.// -->
                        <label for="">{{cart_item.quantity}}</label>
                    </td>
                    <td> 
                        <div class="price-wrap"> 
                            <var class="price">{{cart_item.sub_total}}</var> 
                            <small class="text-muted"> $578.00 each</small> 
                        </div> <!-- price-wrap .// -->
                    </td>
                </tr>
                {%endfor%}
                </tbody>
                </table>
            <button type = "submit" name = "submit" class = "btn btn-primary btn-block">Place Order</button>
            <a href="{% url 'store'%}" class="btn btn-light btn-block">Continue Shopping</a>
        </form>
        </div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->
</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{%endblock%}

Eapp/templates/index.html
{% extends 'base.html' %}
{%load static%}
{%block content%}
<!-- ========================= SECTION MAIN ========================= -->
<section class="section-intro padding-y-sm">
<div class="container">

<div class="intro-banner-wrap">
	<img src="{% static 'images/banners/1.jpg'%}" class="img-fluid rounded">
</div>

</div> <!-- container //  -->
</section>
<!-- ========================= SECTION MAIN END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm">
<div class="container">

<header class="section-heading">
	<a href="store" class="btn btn-outline-primary float-right">See all</a>
	<h3 class="section-title">Popular products</h3>
</header><!-- sect-heading -->


<div class="row">
	{% for product in products %}
	<div class="col-md-3">
		<div class="card card-product-grid">
			<a href="{{product.get_url}}" class="img-wrap"> <img src="{{product.image.url}}"> </a>
			<figcaption class="info-wrap">
					<a href="{{product.get_url}}" class="title">{{product.product_name}}</a>
				<div class="price mt-1">{{product.price}}</div> <!-- price-wrap.// -->
			</figcaption>
		</div>
	</div> <!-- col.// -->
	{%endfor%}
</div> <!-- row.// -->

</div><!-- container // -->
</section>
<!-- ========================= SECTION  END// ========================= -->




<!-- ========================= FOOTER ========================= -->
{%include 'includes/footer.html' %}
<!-- ========================= FOOTER END // ========================= -->

</body>
</html>

{%endblock%}

Eapp/templates/login.html
{% extends "base.html" %}

{% block content %}

<section class="section-conten padding-y" style="min-height:84vh">
    {% if request.GET.command %}
        <div class="container mx-auto alert alert-info text-center" role = "alert" style="max-width: 1024px; margin-top:100px;">
            Thank you for registering with us. We have sent you a verification email to your email address [{{ request.GET.email }}]. Please verify it.
            <br>
            Already verfied? <a href ="{% url 'login' %}">Login</a>
        </div>
    {% else %}
    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
          <h4 class="card-title mb-4">Sign in</h4>
          {% include 'includes/alerts.html' %}
          <form action = "{% url 'login' %}" method = "POST">
              {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" name = "email" >
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" name = "password">
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url 'forgotPassword' %}" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Login  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'register' %}">Sign up</a></p>
         <br><br>
         {% endif %}
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    </section>
{% endblock %}

Eapp/templates/product-detail.html
{%extends 'base.html'%}
{%load static%}
{%block content%}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap"> 
	<div class="img-big-wrap">
	   <a href="#"><img src="{{single_product.image.url}}"></a>
	</div> <!-- img-big-wrap.// -->
	
</article> <!-- gallery-wrap .end// -->
		</aside>
		<main class="col-md-6 border-left">
<form action = "{%url 'add_cart' single_product.id%}" method="POST">
	{%csrf_token%}
<article class="content-body">

<h2 class="title">{{single_product.product_name}}</h2>

<div class="mb-3"> 
	<var class="price h4">{{single_product.price}}</var> 
</div> 

<p>{{single_product.description}}</p>


<hr>
	<div class="row">
		<div class="item-option-select">
			<h6>Choose Color</h6>
			<select name="color" class = "form-control">
				<option value = "" disabled selected>Select</option>
				{% for i in single_product.variation_set.colors %}
					<option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
				{% endfor %}
			</select>
		</div>
	</div> <!-- row.// -->
	<div class="row">
		<div class="item-option-select">
			<h6>Select Size</h6>
			<select name="size" class = "form-control">
				<option value = "" disabled selected>Select</option>
				{% for i in single_product.variation_set.sizes %}
					<option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
				{% endfor %}
			</select>
		</div>
	</div> <!-- row.// -->
	<hr>
	{% if single_product.stock <= 0 %}	
		<h5 class = "text-danger">Out of Stocks</h5>
		{%else%}
		<button type = "submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
	{%endif%}
	</article> <!-- product-info-aside .// -->
	</form>
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">

	<header class="section-heading">
		<h3>Customer Reviews </h3>  
		
	</header>

	<article class="box mb-3">
		<div class="icontext w-100">
			<img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
			<div class="text">
				<span class="date text-muted float-md-right">24.04.2020 </span>  
				<h6 class="mb-1">Mike John </h6>
				
			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
			<p>
				Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip
			</p>	
		</div>
	</article>
</form>

	

	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

</body>
</html>
{%endblock%}

Eapp/templates/register.html
{% extends 'base.html' %}
{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

<!-- ============================ COMPONENT REGISTER   ================================= -->
	<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
      <article class="card-body">
		  {% include 'includes/alerts.html' %}
		<header class="mb-4"><h4 class="card-title">Sign up</h4></header>
		<form action = "{% url 'register' %}" method = "POST">
			{% csrf_token %}
			<!-- {{ form.as_p }} -->
				<div class="form-row">
					<div class="col form-group">
						<label>First name</label>
					  {{form.first_name}}
					</div> <!-- form-group end.// -->
					<div class="col form-group">
						<label>Last name</label>
						{{form.last_name}}
					</div> <!-- form-group end.// -->
				</div> <!-- form-row end.// -->

				<div class="form-row">
					<div class="form-group col-md-6">
					  <label>Email</label>
					  {{form.email}}
					</div> <!-- form-group end.// -->
					<div class="form-group col-md-6">
					  <label>Phone Number</label>
						{{ form.phone_number }}
					</div> <!-- form-group end.// -->
				</div> <!-- form-row.// -->
				<div class="form-row">
					<div class="form-group col-md-6">
						<label>Create password</label>
					    {{ form.password }}
					</div> <!-- form-group end.// --> 
					<div class="form-group col-md-6">
						<label>Repeat password</label>
					    {{ form.confirm_password }}
					</div> <!-- form-group end.// -->  
				</div>
			    <div class="form-group">
			        <button type="submit" class="btn btn-primary btn-block"> Register  </button>
			    </div> <!-- form-group// -->      
			    {{form.email_errors}}
				{{form.non_field_errors}}
			</form>
		</article><!-- card-body.// -->
    </div> <!-- card .// -->
    <p class="text-center mt-4">Have an account? <a href="{% url 'login' %}">Log In</a></p>
    <br><br>
<!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}